"""Tests for json_schema_name and json_schema_name_generator config options."""

import re
from typing import Generic, TypeVar

import pytest

from pydantic import BaseModel, ConfigDict
from pydantic.errors import PydanticUserError
from pydantic.json_schema import models_json_schema


def test_json_schema_name_simple():
    """Test simple string override for json_schema_name."""

    class User1(BaseModel):
        model_config = ConfigDict(json_schema_name='ClientAUser')
        name: str

    class User2(BaseModel):
        model_config = ConfigDict(json_schema_name='ClientBUser')
        name: str

    # Test single model
    schema_a = User1.model_json_schema()
    assert '$defs' not in schema_a  # No nested refs for simple model
    assert schema_a['title'] == 'User1'  # title unchanged

    # Test multiple models with name collision
    _, combined_schema = models_json_schema(
        [
            (User1, 'validation'),
            (User2, 'validation'),
        ]
    )

    # Both models should use their custom names
    assert 'ClientAUser' in combined_schema['$defs']
    assert 'ClientBUser' in combined_schema['$defs']

    # Should NOT have the default collision-resolution names
    assert 'tests__test_json_schema_name__User1' not in combined_schema['$defs']
    assert 'tests__test_json_schema_name__User2' not in combined_schema['$defs']


def test_json_schema_name_with_mode():
    """Test that json_schema_name works with validation and serialization modes."""

    class Model(BaseModel):
        model_config = ConfigDict(json_schema_name='CustomModel')
        name: str

    # Validation mode
    schema_val = Model.model_json_schema(mode='validation')
    assert schema_val['title'] == 'Model'  # title unchanged

    # Serialization mode
    schema_ser = Model.model_json_schema(mode='serialization')
    assert schema_ser['title'] == 'Model'

    # Multiple models with different modes
    _, combined_schema = models_json_schema(
        [
            (Model, 'validation'),
            (Model, 'serialization'),
        ]
    )

    # Should have mode-specific names in defs
    assert 'CustomModel-Input' in combined_schema['$defs'] or 'CustomModel' in combined_schema['$defs']
    assert 'CustomModel-Output' in combined_schema['$defs'] or 'CustomModel' in combined_schema['$defs']


def test_json_schema_name_generator():
    """Test json_schema_name_generator function."""

    def custom_namer(model: type) -> str:
        # Generate name from module and class name
        module_parts = model.__module__.split('.')
        if len(module_parts) >= 2:
            return f'{module_parts[-1].title()}{model.__name__}'
        return model.__name__

    class User1(BaseModel):
        model_config = ConfigDict(json_schema_name_generator=custom_namer)
        name: str

    class User2(BaseModel):
        model_config = ConfigDict(json_schema_name_generator=custom_namer)
        email: str

    _, combined_schema = models_json_schema(
        [
            (User1, 'validation'),
            (User2, 'validation'),
        ]
    )

    # Names should be generated by the function
    expected_a = custom_namer(User1)
    expected_b = custom_namer(User2)

    assert expected_a in combined_schema['$defs']
    assert expected_b in combined_schema['$defs']


def test_json_schema_name_precedence_over_generator():
    """Test that json_schema_name takes precedence over json_schema_name_generator."""

    def namer(model: type) -> str:
        return f'Generated{model.__name__}'

    class Model(BaseModel):
        model_config = ConfigDict(json_schema_name='ExplicitName', json_schema_name_generator=namer)
        name: str

    schema = Model.model_json_schema()

    # When using with other models, the explicit name should be used
    class OtherModel(BaseModel):
        model: Model

    schema = OtherModel.model_json_schema()
    assert 'ExplicitName' in schema['$defs']
    assert 'GeneratedModel' not in schema['$defs']


def test_json_schema_name_with_nested_models():
    """Test json_schema_name with nested model references."""

    class Inner(BaseModel):
        model_config = ConfigDict(json_schema_name='CustomInner')
        value: int

    class Outer(BaseModel):
        model_config = ConfigDict(json_schema_name='CustomOuter')
        inner: Inner

    schema = Outer.model_json_schema()

    # Both custom names should appear in $defs
    assert 'CustomInner' in schema['$defs']
    assert 'CustomOuter' not in schema['$defs']  # Outer is the root, not in defs
    assert schema['title'] == 'Outer'  # title remains unchanged


def test_json_schema_name_separation_from_title():
    """Test that json_schema_name and title are independent."""

    class Model(BaseModel):
        model_config = ConfigDict(json_schema_name='SchemaName', title='Model Title')
        name: str

    class Container(BaseModel):
        model: Model

    schema = Container.model_json_schema()

    # The def should use json_schema_name
    assert 'SchemaName' in schema['$defs']

    # The title in the def should still use the title config
    assert schema['$defs']['SchemaName']['title'] == 'Model Title'


def test_json_schema_name_no_collision():
    """Test that when two models specify the same json_schema_name, an error is raised."""

    # Two models with same name from different modules
    class User1(BaseModel):
        model_config = ConfigDict(json_schema_name='UserCustom')
        field_a: str

    class User2(BaseModel):
        model_config = ConfigDict(json_schema_name='UserCustom')
        field_b: str

    # When both use the same custom name, it should raise an error
    with pytest.raises(
        PydanticUserError,
        match=re.escape('Multiple models have the same JSON schema name "UserCustom"'),
    ):
        models_json_schema(
            [
                (User1, 'validation'),
                (User2, 'validation'),
            ]
        )


def test_json_schema_name_with_generics():
    """Test that generics with custom names need unique names for each parametrization."""

    T = TypeVar('T')

    # This will fail because the same name is used for different generic parametrizations
    class Container(BaseModel, Generic[T]):
        model_config = ConfigDict(json_schema_name='CustomContainer')
        value: T

    class Model(BaseModel):
        container_int: Container[int]
        container_str: Container[str]

    # Should raise an error because Container[int] and Container[str] are different types
    # but both would get the same custom name
    with pytest.raises(PydanticUserError, match='Multiple models have the same JSON schema name'):
        Model.model_json_schema()


def test_json_schema_name_empty_string():
    """Test that empty string is not allowed for json_schema_name."""

    class Model(BaseModel):
        model_config = ConfigDict(json_schema_name='')
        name: str

    # Empty string should either raise an error or fall back to default
    # The behavior should be well-defined
    schema = Model.model_json_schema()
    # Should have a valid title
    assert schema['title']


def test_json_schema_name_generator_returns_none():
    """Test behavior when json_schema_name_generator returns None."""

    def conditional_namer(model: type) -> str | None:
        if model.__name__.startswith('Custom'):
            return f'Named{model.__name__}'
        return None

    class CustomModel(BaseModel):
        model_config = ConfigDict(json_schema_name_generator=conditional_namer)
        name: str

    class RegularModel(BaseModel):
        model_config = ConfigDict(json_schema_name_generator=conditional_namer)
        name: str

    _, combined_schema = models_json_schema(
        [
            (CustomModel, 'validation'),
            (RegularModel, 'validation'),
        ]
    )

    defs_keys = list(combined_schema['$defs'].keys())

    # CustomModel should have custom name
    assert any('NamedCustomModel' in key for key in defs_keys)

    # RegularModel should use default naming
    assert any('RegularModel' in key for key in defs_keys)


def test_json_schema_name_backward_compatibility():
    """Test that models without json_schema_name work as before."""

    class ModelA(BaseModel):
        name: str

    class ModelB(BaseModel):
        name: str

    _, combined_schema = models_json_schema(
        [
            (ModelA, 'validation'),
            (ModelB, 'validation'),
        ]
    )

    # Should use default names
    assert 'ModelA' in combined_schema['$defs']
    assert 'ModelB' in combined_schema['$defs']


def test_json_schema_name_special_characters():
    """Test json_schema_name with special characters."""

    class Model(BaseModel):
        model_config = ConfigDict(json_schema_name='Custom-Model_v2')
        name: str

    class Container(BaseModel):
        model: Model

    schema = Container.model_json_schema()

    # Name should be normalized (dashes converted to valid characters)
    # The exact normalization is implementation-dependent
    assert any('Custom' in key and 'Model' in key for key in schema['$defs'].keys())


def test_json_schema_name_with_model_title_generator():
    """Test interaction between json_schema_name and model_title_generator."""

    def title_gen(model: type) -> str:
        return f'Title: {model.__name__}'

    class Model(BaseModel):
        model_config = ConfigDict(json_schema_name='CustomDef', model_title_generator=title_gen)
        name: str

    class Container(BaseModel):
        model: Model

    schema = Container.model_json_schema()

    # Def name should use json_schema_name
    assert 'CustomDef' in schema['$defs']

    # Title should use model_title_generator
    assert schema['$defs']['CustomDef']['title'] == title_gen(Model)


def test_json_schema_name_custom_vs_default_collision():
    """Test that collision between custom name and default name raises an error."""

    # Model with custom name that collides with another model's default name
    class UserModel(BaseModel):
        model_config = ConfigDict(json_schema_name='DefaultNameModel')
        name: str

    # Model whose default name will collide with UserModel's custom name
    class DefaultNameModel(BaseModel):
        email: str

    # Should raise error about collision between custom and default names
    with pytest.raises(PydanticUserError, match='Custom JSON schema name "DefaultNameModel" collides'):
        models_json_schema(
            [
                (UserModel, 'validation'),
                (DefaultNameModel, 'validation'),
            ]
        )
